# Generated by Django 4.2.6 on 2023-11-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caregory',
            new_name='category',
        ),
    ]
